# Site configuration
# 1. Installed Gems
# 2. Gem settings
# 3. Jekyll settings
# 4. Collections
# 5. Jekyll collections settings
# 6. Site settings
# 7. Site navigation

# 1. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 2. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page

author: Sidney Goveia # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Geosaber # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/Geosaber
    - https://www.facebook.com/Sidney.Geosaber
    - https://www.linkedin.com/company/geosaber
    - https://plus.google.com/+geosaber
    - https://github.com/geosaber

# 3. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Sao_Paulo # Timezone for blog posts and alike

# 4. Collections
collections:
  posts:
    title: Blog # Needed for Siteleaf
    output: true
    description: "Publicações" # The post list page content
    feature_text: |
      Benvindo ao Blog
    feature_image: "https://unsplash.it/1300/400?image=1067"

# 5. Jekyll collections settings
defaults:
  -
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 6. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: pt-BR # Set the site language
title: "Geosaber" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Portal de Geotecnologias Livres" # Site description and default description, also used in jekyll-seo-tag
url: "https://geosaber.github.io" # Site url, also used in jekyll-seo-tag
baseurl: "/r4geo"
repo: "https://github.com/geosaber/r4geo"
email: "contato@geosaber.com.br"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
#avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 7. Site navigation
navigation_header:
  Início: /
  Cursos: /elements/
  Blog: /blog/
  Tutoriais: /tutorial/
  Serviços: /categories/
  Sobre: /about/
  Contato: https://github.com/geosaber
  Busca: /search/

navigation_footer:
  S.S.Goveia "http://www.geosaber.com.br"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  #Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/company/geosaber
  #Google+: https://plus.google.com/+DavidDarnes
  Facebook: https://www.facebook.com/Sidney.Geosaber
  GitHub: https://github.com/daviddarnes
  link: http://www.geosaber.com.br
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  Facebook: "#3B5998"
  #Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: "#1DA1F2"
